recipe: default.v1

language: en

pipeline:
  - name: nlu_tok.AnotherWhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: nlu_dense.BytePairFeaturizer
    lang: en 
    dim: 25
    vs: 1000
  - name: nlu_sparse.TfIdfFeaturizer
    analyzer: char
    min_ngram: 2
    max_ngram: 3
  - name: nlu_clf.LogisticRegressionClassifier

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
